services:
  db:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
    ports:
      - "27017:27017"

  api:
    image: dixennaxos/tracktruck:api
    container_name: tracktruck-api
    env_file: ./api/.env
    environment:
      MONGO_URI: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tracktruck-api.rule=Host(`api.tracktruck.dixen.fr`)"
      - "traefik.http.routers.tracktruck-api.entrypoints=websecure"
      - "traefik.http.routers.tracktruck-api.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
      - backend
    volumes:
    - ./api/firebase-service-account.json:/app/firebase-service-account.json:ro
    depends_on:
      - db

volumes:
  mongodb_data:

networks:
  traefik:
    external: true
  backend:
    driver: bridge
