name: truck_map
description: "Map app with itinerary display and polling"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Map
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_svg: ^2.0.10+1

  # Location
  geolocator: ^13.0.2

  # Networking
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/road_signs/
