import type { Driver, Skill, StatusMeta, Vehicle, DriverStatus } from "./types";

export const VEHICLES: Vehicle[] = [
  { id: "V-01", driverId: "D-001", status: "en-route",  load: 82, eta: "14:30", from: "Rungis",        to: "Paris 15e" },
  { id: "V-02", driverId: "D-002", status: "livraison", load: 60, eta: "15:00", from: "Gennevilliers", to: "Versailles" },
  { id: "V-03", driverId: "D-003", status: "retour",    load: 18, eta: "16:15", from: "Boulogne",      to: "Rungis" },
  { id: "V-04", driverId: "D-004", status: "en-route",  load: 74, eta: "15:45", from: "Neuilly",       to: "Orly" },
  { id: "V-05", driverId: "D-005", status: "arret",     load: 45, eta: "—",     from: "A6",            to: "Lyon N" },
];

export const SKILLS: Skill[] = [
  { id: "pl",   label: "Poids lourds",         family: "Permis",        desc: "Permis C / CE, 3,5 t et +" },
  { id: "adr",  label: "Matières dangereuses", family: "Habilitation",  desc: "Certificat ADR en cours de validité" },
  { id: "frig", label: "Frigo / Grand froid",  family: "Matériel",      desc: "Température contrôlée, –25°C min." },
  { id: "exp",  label: "Express",              family: "Opérationnel",  desc: "Livraisons urgentes < 4h" },
  { id: "frag", label: "Fragile",              family: "Opérationnel",  desc: "Colis fragiles, arrimage spécifique" },
  { id: "int",  label: "International",        family: "Zone",          desc: "UE élargie, documents douaniers" },
  { id: "prod", label: "Produits frais",       family: "Matériel",      desc: "Chaîne du froid +2 / +8°C" },
  { id: "nuit", label: "Nuit",                 family: "Opérationnel",  desc: "Plages 22h–06h" },
  { id: "cit",  label: "Citerne",              family: "Matériel",      desc: "Transport liquides, FIMO citerne" },
];

export const DRIVERS: Driver[] = [
  {
    id: "D-001", matricule: "TT-001", firstName: "Jean", lastName: "Dupont",
    status: "en-service", rating: 4.8, missions: 156, since: "2019-03-12",
    phone: "+33 6 12 34 56 78", email: "jean.dupont@tracktruck.fr",
    vehicle: "V-01", license: "C, CE", expiry: "2028-06-30",
    skills: ["pl","adr","frig"],
    zones: ["Île-de-France", "Hauts-de-France"],
    availability: { mon:1, tue:1, wed:1, thu:1, fri:1, sat:0, sun:0 },
    nextLeave: "12 mai → 16 mai",
    onTimeRate: 0.96, incidents30d: 0,
    avatarTone: 220, initials: "JD",
    recent: [
      { id: "C-2845", date: "23 avr.", route: "Rungis → Paris 15e", status: "Livrée",  kms: 24 },
      { id: "C-2811", date: "22 avr.", route: "Rungis → Nanterre",  status: "Livrée",  kms: 31 },
      { id: "C-2790", date: "21 avr.", route: "Rungis → Melun",     status: "Livrée",  kms: 58 },
    ],
  },
  {
    id: "D-002", matricule: "TT-002", firstName: "Marie", lastName: "Martin",
    status: "en-service", rating: 4.9, missions: 203, since: "2017-09-01",
    phone: "+33 6 23 45 67 89", email: "marie.martin@tracktruck.fr",
    vehicle: "V-02", license: "C, CE, D", expiry: "2027-11-12",
    skills: ["pl","exp","frag"],
    zones: ["Île-de-France"],
    availability: { mon:1, tue:1, wed:1, thu:1, fri:1, sat:1, sun:0 },
    nextLeave: "—",
    onTimeRate: 0.98, incidents30d: 1,
    avatarTone: 340, initials: "MM",
    recent: [
      { id: "C-2846", date: "23 avr.", route: "Gennevilliers → Versailles", status: "En cours", kms: 27 },
      { id: "C-2814", date: "22 avr.", route: "Paris 8 → Saint-Cloud",       status: "Livrée",   kms: 18 },
    ],
  },
  {
    id: "D-003", matricule: "TT-003", firstName: "Pierre", lastName: "Bernard",
    status: "disponible", rating: 4.7, missions: 128, since: "2020-02-18",
    phone: "+33 6 34 56 78 90", email: "pierre.bernard@tracktruck.fr",
    vehicle: "V-03", license: "C, CE", expiry: "2026-08-05",
    skills: ["pl","frag","int"],
    zones: ["France", "Benelux", "Allemagne"],
    availability: { mon:1, tue:1, wed:1, thu:0, fri:1, sat:0, sun:0 },
    nextLeave: "2 mai → 9 mai",
    onTimeRate: 0.94, incidents30d: 0,
    avatarTone: 150, initials: "PB",
    recent: [
      { id: "C-2801", date: "22 avr.", route: "Le Havre → Reims", status: "Livrée", kms: 312 },
      { id: "C-2777", date: "20 avr.", route: "Paris → Liège",    status: "Livrée", kms: 420 },
    ],
  },
  {
    id: "D-004", matricule: "TT-004", firstName: "Sophie", lastName: "Laurent",
    status: "en-service", rating: 4.9, missions: 241, since: "2016-05-22",
    phone: "+33 6 45 67 89 01", email: "sophie.laurent@tracktruck.fr",
    vehicle: "V-04", license: "C, CE", expiry: "2029-01-18",
    skills: ["pl","prod","exp"],
    zones: ["Île-de-France", "Normandie"],
    availability: { mon:1, tue:1, wed:1, thu:1, fri:1, sat:0, sun:0 },
    nextLeave: "—",
    onTimeRate: 0.97, incidents30d: 0,
    avatarTone: 30, initials: "SL",
    recent: [
      { id: "C-2848", date: "23 avr.", route: "Rungis → Neuilly", status: "En cours", kms: 12 },
      { id: "C-2802", date: "22 avr.", route: "Rungis → Rouen",   status: "Livrée",   kms: 134 },
    ],
  },
  {
    id: "D-005", matricule: "TT-005", firstName: "Karim", lastName: "Benali",
    status: "repos", rating: 4.6, missions: 89, since: "2021-10-04",
    phone: "+33 6 56 78 90 12", email: "karim.benali@tracktruck.fr",
    vehicle: "V-05", license: "C", expiry: "2027-03-22",
    skills: ["pl","nuit"],
    zones: ["Île-de-France", "Bourgogne"],
    availability: { mon:0, tue:1, wed:1, thu:1, fri:1, sat:1, sun:0 },
    nextLeave: "Repos hebdo",
    onTimeRate: 0.91, incidents30d: 2,
    avatarTone: 275, initials: "KB",
    recent: [
      { id: "C-2789", date: "21 avr.", route: "Rungis → Dijon", status: "Livrée", kms: 315 },
    ],
  },
  {
    id: "D-006", matricule: "TT-006", firstName: "Léa", lastName: "Moreau",
    status: "disponible", rating: 4.8, missions: 167, since: "2018-11-29",
    phone: "+33 6 67 89 01 23", email: "lea.moreau@tracktruck.fr",
    vehicle: "—", license: "C, CE, ADR", expiry: "2028-09-10",
    skills: ["pl","adr","cit"],
    zones: ["France"],
    availability: { mon:1, tue:1, wed:1, thu:1, fri:1, sat:0, sun:0 },
    nextLeave: "—",
    onTimeRate: 0.95, incidents30d: 0,
    avatarTone: 195, initials: "LM",
    recent: [
      { id: "C-2798", date: "21 avr.", route: "Feyzin → Fos-sur-Mer", status: "Livrée", kms: 302 },
    ],
  },
  {
    id: "D-007", matricule: "TT-007", firstName: "Antoine", lastName: "Rossi",
    status: "conges", rating: 4.7, missions: 98, since: "2020-07-14",
    phone: "+33 6 78 90 12 34", email: "antoine.rossi@tracktruck.fr",
    vehicle: "—", license: "C, CE", expiry: "2027-12-01",
    skills: ["pl","frag","int"],
    zones: ["France", "Italie", "Espagne"],
    availability: { mon:0, tue:0, wed:0, thu:0, fri:0, sat:0, sun:0 },
    nextLeave: "Congés 20 avr. → 3 mai",
    onTimeRate: 0.93, incidents30d: 0,
    avatarTone: 10, initials: "AR",
    recent: [],
  },
  {
    id: "D-008", matricule: "TT-008", firstName: "Nadia", lastName: "Chevalier",
    status: "disponible", rating: 5.0, missions: 312, since: "2014-02-03",
    phone: "+33 6 89 01 23 45", email: "nadia.chevalier@tracktruck.fr",
    vehicle: "—", license: "C, CE, ADR", expiry: "2030-05-28",
    skills: ["pl","adr","frig","prod"],
    zones: ["Île-de-France", "Grand Est"],
    availability: { mon:1, tue:1, wed:1, thu:1, fri:1, sat:1, sun:1 },
    nextLeave: "—",
    onTimeRate: 0.99, incidents30d: 0,
    avatarTone: 290, initials: "NC",
    recent: [
      { id: "C-2810", date: "22 avr.", route: "Rungis → Strasbourg", status: "Livrée", kms: 490 },
    ],
  },
];

export const STATUS_META: Record<DriverStatus, StatusMeta> = {
  "en-service": { label: "En service", dot: "oklch(0.62 0.14 150)", text: "var(--success)",   bg: "var(--success-soft)" },
  "disponible": { label: "Disponible", dot: "oklch(0.55 0.18 265)", text: "var(--accent-ink)", bg: "var(--accent-soft)" },
  "repos":      { label: "Repos",      dot: "oklch(0.6 0.01 260)",  text: "var(--ink-3)",     bg: "oklch(0.22 0.01 260 / 0.06)" },
  "conges":     { label: "Congés",     dot: "oklch(0.72 0.14 65)",  text: "var(--warn)",      bg: "var(--warn-soft)" },
};
