import type { Driver, Skill, Vehicle } from "./types";

export const VEHICLES: Vehicle[] = [
  {
    id: "V-01",
    driverId: "D-001",

    load: 82,
    eta: "14:30",
    from: "Rungis",
    to: "Paris 15e",
  },
  {
    id: "V-02",
    driverId: "D-002",

    load: 60,
    eta: "15:00",
    from: "Gennevilliers",
    to: "Versailles",
  },
  {
    id: "V-03",
    driverId: "D-003",

    load: 18,
    eta: "16:15",
    from: "Boulogne",
    to: "Rungis",
  },
  {
    id: "V-04",
    driverId: "D-004",

    load: 74,
    eta: "15:45",
    from: "Neuilly",
    to: "Orly",
  },
  {
    id: "V-05",
    driverId: "D-005",

    load: 45,
    eta: "—",
    from: "A6",
    to: "Lyon N",
  },
];

export const SKILLS: Skill[] = [
  {
    id: "pl",
    label: "Poids lourds",
    family: "Permis",
    desc: "Permis C / CE, 3,5 t et +",
  },
  {
    id: "adr",
    label: "Matières dangereuses",
    family: "Habilitation",
    desc: "Certificat ADR en cours de validité",
  },
  {
    id: "frig",
    label: "Frigo / Grand froid",
    family: "Matériel",
    desc: "Température contrôlée, –25°C min.",
  },
  {
    id: "exp",
    label: "Express",
    family: "Opérationnel",
    desc: "Livraisons urgentes < 4h",
  },
  {
    id: "frag",
    label: "Fragile",
    family: "Opérationnel",
    desc: "Colis fragiles, arrimage spécifique",
  },
  {
    id: "int",
    label: "International",
    family: "Zone",
    desc: "UE élargie, documents douaniers",
  },
  {
    id: "prod",
    label: "Produits frais",
    family: "Matériel",
    desc: "Chaîne du froid +2 / +8°C",
  },
  { id: "nuit", label: "Nuit", family: "Opérationnel", desc: "Plages 22h–06h" },
  {
    id: "cit",
    label: "Citerne",
    family: "Matériel",
    desc: "Transport liquides, FIMO citerne",
  },
];

export const DRIVERS: Driver[] = [
  {
    id: "D-001",
    firstName: "Jean",
    lastName: "Dupont",
    phone: "+33 6 12 34 56 78",
    email: "jean.dupont@tracktruck.fr",
    skills: ["pl", "adr", "frig"],
    zones: ["Île-de-France", "Hauts-de-France"],
    avatarTone: 220,
    initials: "JD",
  },
  {
    id: "D-002",
    firstName: "Marie",
    lastName: "Martin",
    phone: "+33 6 23 45 67 89",
    email: "marie.martin@tracktruck.fr",
    skills: ["pl", "exp", "frag"],
    zones: ["Île-de-France"],
    avatarTone: 340,
    initials: "MM",
  },
  {
    id: "D-003",
    firstName: "Pierre",
    lastName: "Bernard",
    phone: "+33 6 34 56 78 90",
    email: "pierre.bernard@tracktruck.fr",
    skills: ["pl", "frag", "int"],
    zones: ["France", "Benelux", "Allemagne"],
    avatarTone: 150,
    initials: "PB",
  },
  {
    id: "D-004",
    firstName: "Sophie",
    lastName: "Laurent",
    phone: "+33 6 45 67 89 01",
    email: "sophie.laurent@tracktruck.fr",
    skills: ["pl", "prod", "exp"],
    zones: ["Île-de-France", "Normandie"],
    avatarTone: 30,
    initials: "SL",
  },
  {
    id: "D-005",
    firstName: "Karim",
    lastName: "Benali",
    phone: "+33 6 56 78 90 12",
    email: "karim.benali@tracktruck.fr",
    skills: ["pl", "nuit"],
    zones: ["Île-de-France", "Bourgogne"],
    avatarTone: 275,
    initials: "KB",
  },
  {
    id: "D-006",
    firstName: "Léa",
    lastName: "Moreau",
    phone: "+33 6 67 89 01 23",
    email: "lea.moreau@tracktruck.fr",
    skills: ["pl", "adr", "cit"],
    zones: ["France"],
    avatarTone: 195,
    initials: "LM",
  },
  {
    id: "D-007",
    firstName: "Antoine",
    lastName: "Rossi",
    phone: "+33 6 78 90 12 34",
    email: "antoine.rossi@tracktruck.fr",
    skills: ["pl", "frag", "int"],
    zones: ["France", "Italie", "Espagne"],
    avatarTone: 10,
    initials: "AR",
  },
  {
    id: "D-008",
    firstName: "Nadia",
    lastName: "Chevalier",
    phone: "+33 6 89 01 23 45",
    email: "nadia.chevalier@tracktruck.fr",
    skills: ["pl", "adr", "frig", "prod"],
    zones: ["Île-de-France", "Grand Est"],
    avatarTone: 290,
    initials: "NC",
  },
];
